package main

import (
	"os"
	"text/template"

	"github.com/kendfss/but"
	"github.com/kendfss/fopa/internal"
)

func main() {
	f := but.Mustv(os.Create("parsed.go"))
	but.Must(template.Must(template.New("").Parse(templateString)).Execute(f, struct {
		Rules []internal.Rule
		Chars []string
	}{
		Rules: internal.GetForbiddenRules(),
		Chars: internal.GetForbiddenChars(),
	}))
}

const templateString = `// generated by go generate
// do not modify by hand

package internal

var ForbiddenRules = []Rule{
{{- range .Rules }}
	{Symb: {{ printf "%q" .Symb }}, Desc: {{ printf "%q" .Desc }}},
{{- end }}
}

var ForbiddenChars = []string{
{{- range .Chars }}
	{{ printf "%q" . }},
{{- end }}
}
`
